### ISSUE TITLE
Isomorphism problem

### ISSUE THREAD

**Issue by carlesnunez** [Setsun/react-choreography#31]
Hello! First of all thank you for developing this library.

I was wondering if I can use it on my isomorphic page and once I installed the package I'm having a window undefined error from server. It seems that the dist/index.js file have an IFEE that injects the window as argument:

```javascript
!(function(t, e) {
  if ('object' == typeof exports && 'object' == typeof module)
    module.exports = e(require('react'), require('react-transition-group'));
  else if ('function' == typeof define && define.amd) define(['react', 'react-transition-group'], e);
  else {
    var r =
      'object' == typeof exports
        ? e(require('react'), require('react-transition-group'))
        : e(t.React, t.ReactTransitionGroup);
    for (var n in r) ('object' == typeof exports ? exports : t)[n] = r[n];
  }
})(window, function(t, e) {

......
.......
......
.......
```

**Comment by setsun** [comment]
@carlesnunez thanks for letting me know! 

This looks like my webpack configuration, and how I'm marking `react` / `react-transition-group` as external dependencies. 

I'll have a moment later today to investigate and potentially publish a new version 👍

**Comment by andresz1** [comment]
@Setsun could be related with the webpack [target](https://webpack.js.org/concepts/targets/#multiple-targets) I think

**Comment by setsun** [comment]
That pointed me in the right direction, thanks @andresz1!

Just published `v4.2.0` off of this commit: https://github.com/Setsun/react-transition-components/commit/f0d9c72fd804fffcd382b59beac8731456478583

The main change is that there are now two bundles that are created for `node`  and the `browser`.

In the `package.json`, the `main` property points to the `node` bundle, and the `browser` property points to the `browser` bundle. 

Let me know if that fixes the issue @carlesnunez.

**Comment by andresz1** [comment]
It works @Setsun. I think that we can close the issue 👍

**Comment by setsun** [comment]
@carlesnunez looks like this is resolved, please re-open a new issue if there is anything else!
